# Generated by Django 2.2.6 on 2022-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_pk', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=8, max_digits=16)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('jsontext', models.TextField()),
            ],
        ),
    ]
